[package]
name = "daemon"
version = "0.1.0"
authors = ["Alain Galvan"]

[dependencies]
iron = "0.5.0"
bodyparser = "0.8.0"
rust-crypto = "0.2.36"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
